export const SITE_CONFIG = {
  name: 'ShowcasePro',
  title: 'John Doe - Full Stack Developer',
  description: 'Professional portfolio and blog showcasing modern web development projects and insights.',
  author: 'John Doe',
  email: 'john.doe@example.com',
  location: 'San Francisco, CA',
  url: 'https://your-domain.github.io/showcasepro',
  social: {
    github: 'https://github.com/johndoe',
    linkedin: 'https://linkedin.com/in/johndoe',
    twitter: 'https://twitter.com/johndoe',
    email: 'mailto:john.doe@example.com',
  },
  navigation: [
    { label: 'Home', href: '#home' },
    { label: 'About', href: '#about' },
    { label: 'Projects', href: '#projects' },
    { label: 'Blog', href: '#blog' },
    { label: 'Contact', href: '#contact' },
  ],
};

export const SKILLS = [
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Node.js',
  'Python',
  'PostgreSQL',
  'MongoDB',
  'AWS',
  'Docker',
  'Git',
  'GraphQL',
  'REST APIs',
  'Tailwind CSS',
  'Jest',
  'Cypress',
];

export const TECH_COLORS: Record<string, string> = {
  JavaScript: 'bg-yellow-100 text-yellow-800',
  TypeScript: 'bg-blue-100 text-blue-800',
  React: 'bg-cyan-100 text-cyan-800',
  'Next.js': 'bg-gray-100 text-gray-800',
  'Node.js': 'bg-green-100 text-green-800',
  Python: 'bg-green-100 text-green-800',
  PostgreSQL: 'bg-blue-100 text-blue-800',
  MongoDB: 'bg-green-100 text-green-800',
  AWS: 'bg-orange-100 text-orange-800',
  Docker: 'bg-blue-100 text-blue-800',
  Git: 'bg-orange-100 text-orange-800',
  GraphQL: 'bg-pink-100 text-pink-800',
  'REST APIs': 'bg-green-100 text-green-800',
  'Tailwind CSS': 'bg-cyan-100 text-cyan-800',
  Jest: 'bg-red-100 text-red-800',
  Cypress: 'bg-gray-100 text-gray-800',
  HTML: 'bg-orange-100 text-orange-800',
  CSS: 'bg-blue-100 text-blue-800',
  SCSS: 'bg-pink-100 text-pink-800',
  Vue: 'bg-green-100 text-green-800',
  Angular: 'bg-red-100 text-red-800',
  Express: 'bg-gray-100 text-gray-800',
  Prisma: 'bg-gray-100 text-gray-800',
  Redis: 'bg-red-100 text-red-800',
  Kubernetes: 'bg-blue-100 text-blue-800',
};
